version: '3.8'

services:
  # Banco de dados PostgreSQL
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: biblioteca_digital_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Rails
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/biblioteca_digital_development
      RAILS_ENV: development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    command: >
      sh -c "
        bundle install &&
        rails db:create db:migrate db:seed &&
        rails server -b 0.0.0.0 -p 3000
      "

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      REACT_APP_API_URL: http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    depends_on:
      - api

volumes:
  postgres_data:
  bundle_cache:
